name: Publish Gradle
description: |
  Builds and publishes versioned build artifacts for a gradle project.
  Uses the 'reckon' plugin (https://github.com/ajoberstar/reckon) to determine version.
  By default, simply builds the project.
  If the last commit message contains any of the terms [MAJOR, BREAKING], a new major version is published.
  If the last commit message contains any of the terms [PATCH, HOTFIX], a new patch version is published.

inputs:
  java-version:
    description: Java version to run against
    required: true
  java-distribution:
    description: Java distribution to run against
    required: true
    default: temurin
  build-task:
    description: Basic build task
    required: true
    default: build
  publish-task:
    description: Artifact publishing task
    required: true
    default: publish
  token:
    description: Token for Github maven repository read/write
    required: true

runs:
  using: composite
  steps:
    - id: java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        cache: gradle
        distribution: ${{ inputs.java-distribution }}

    - id: build
      shell: bash
      run: |
        msg="${{ github.event.head_commit.message }}"

        case "$msg" in
          *MAJOR* | *BREAKING*)
            scope=major
            ;;
          *MINOR*)
            scope=minor
            ;;
          *PATCH* | *HOTFIX*)
            scope=patch
            ;;
        esac

        if [ -n "$scope" ]; then
          task="${{ inputs.publish-task }} reckonTagPush -Preckon.stage=final -Preckon.scope=$scope"
        else
          task="${{ inputs.build-task }}"
        fi

        ./gradlew "$task" --no-daemon
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
